name: merged_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - cuda-nvcc=11.8*
  - cuda-libraries-dev=11.8*
  - pytorch=2.1.0=py3.8_cuda11.8*
  - torchvision=0.16.0=py38_cu118
  - lit=17.0.6
  - cmake=3.27.9
  - ninja=1.11.1
  - pip:
      - omegaconf==2.3.0
      - jaxtyping==0.2.19
      - typeguard==4.1.5
      - nerfacc==0.3.3
      - pyrender==0.1.45
      - diffusers[torch]==0.19.3
      - transformers==4.28.1
      - accelerate==0.24.1
      - opencv-python==4.8.1.78
      - tensorboard==2.14.0
      - matplotlib==3.7.4
      - imageio==2.33.0
      - imageio[ffmpeg]==2.33.0
      - libigl==2.5.0
      - xatlas==0.0.8
      - trimesh[easy]==4.0.5
      - networkx==3.1
      - pysdf==0.1.9
      - PyMCubes==0.1.4
      - wandb==0.16.0
      - gradio==3.50.2
      - torchmetrics==1.2.0
      - xformers==0.0.22.post7+cu118
      - bitsandbytes==0.38.1
      - sentencepiece==0.1.99
      - safetensors==0.4.1
      - huggingface_hub==0.16.4
      - einops==0.7.0
      - kornia==0.7.0
      - taming-transformers-rom1504==0.0.6
      - controlnet_aux==0.0.7
      - torch_efficient_distloss==0.1.3
      - mediapy==1.1.9
      - plyfile==1.0.2
      - rembg==2.0.52
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - easydict==1.11
      - albumentations==0.5.2
      - webdataset==0.2.79
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
      - git+https://github.com/NVlabs/nvdiffrast.git
      - git+https://github.com/ashawkey/envlight.git
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/ashawkey/kiuikit
      - git+https://github.com/luca-medeiros/lang-segment-anything.git
      - gaussiansplatting/submodules/diff-gaussian-rasterization
      - gaussiansplatting/submodules/simple-knn
